default_platform(:ios)

platform :ios do

  desc "Run tests"
  lane :tests do
    run_tests(
      devices: ["iPhone 16 Pro"],
      scheme: "Quizzy",
      skip_testing: ["QuizzyUITests"]
    )
  end

  desc "Build app"
  lane :build do
    gym(
      scheme: "Quizzy"
    )
  end

end